# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='defect',
            field=models.CharField(default='\u043f\u043e\u0432\u0440\u0435\u0436\u0434\u0435\u043d\u0438\u044f', max_length=200),
            preserve_default=False,
        ),
    ]
