# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-02 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0003_car_defect'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='details',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
