# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0004_car_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='region',
            field=models.CharField(default='\u041c\u043e\u0441\u043a\u0432\u0430', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='tariff',
            field=models.CharField(default='\u042d\u043a\u043e\u043d\u043e\u043c', max_length=200),
            preserve_default=False,
        ),
    ]
